name: moci_petcare
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.3.0
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.8.4
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  go_router: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true
